// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_Address1_AddressType
    {
        /// <summary>
        /// <para>Bill To</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Bill To")]
        BillTo = 1,

        /// <summary>
        /// <para>Ship To</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Ship To")]
        ShipTo = 2,

        /// <summary>
        /// <para>Primary</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Primary")]
        Primary = 3,

        /// <summary>
        /// <para>Other</para>
        /// <para>Value = 4</para>
        /// </summary>
        [Description("Other")]
        Other = 4,
    }
}
