// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_Industry
    {
        /// <summary>
        /// <para>Accounting</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Accounting")]
        Accounting = 1,

        /// <summary>
        /// <para>Agriculture and Non-petrol Natural Resource Extraction</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Agriculture and Non-petrol Natural Resource Extraction")]
        AgricultureAndNon_petrolNaturalResourceExtraction = 2,

        /// <summary>
        /// <para>Broadcasting Printing and Publishing</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Broadcasting Printing and Publishing")]
        BroadcastingPrintingAndPublishing = 3,

        /// <summary>
        /// <para>Brokers</para>
        /// <para>Value = 4</para>
        /// </summary>
        [Description("Brokers")]
        Brokers = 4,

        /// <summary>
        /// <para>Building Supply Retail</para>
        /// <para>Value = 5</para>
        /// </summary>
        [Description("Building Supply Retail")]
        BuildingSupplyRetail = 5,

        /// <summary>
        /// <para>Business Services</para>
        /// <para>Value = 6</para>
        /// </summary>
        [Description("Business Services")]
        BusinessServices = 6,

        /// <summary>
        /// <para>Consulting</para>
        /// <para>Value = 7</para>
        /// </summary>
        [Description("Consulting")]
        Consulting = 7,

        /// <summary>
        /// <para>Consumer Services</para>
        /// <para>Value = 8</para>
        /// </summary>
        [Description("Consumer Services")]
        ConsumerServices = 8,

        /// <summary>
        /// <para>Design, Direction and Creative Management</para>
        /// <para>Value = 9</para>
        /// </summary>
        [Description("Design, Direction and Creative Management")]
        Design_DirectionAndCreativeManagement = 9,

        /// <summary>
        /// <para>Distributors, Dispatchers and Processors</para>
        /// <para>Value = 10</para>
        /// </summary>
        [Description("Distributors, Dispatchers and Processors")]
        Distributors_DispatchersAndProcessors = 10,

        /// <summary>
        /// <para>Doctor's Offices and Clinics</para>
        /// <para>Value = 11</para>
        /// </summary>
        [Description("Doctor's Offices and Clinics")]
        DoctorsOfficesAndClinics = 11,

        /// <summary>
        /// <para>Durable Manufacturing</para>
        /// <para>Value = 12</para>
        /// </summary>
        [Description("Durable Manufacturing")]
        DurableManufacturing = 12,

        /// <summary>
        /// <para>Eating and Drinking Places</para>
        /// <para>Value = 13</para>
        /// </summary>
        [Description("Eating and Drinking Places")]
        EatingAndDrinkingPlaces = 13,

        /// <summary>
        /// <para>Entertainment Retail</para>
        /// <para>Value = 14</para>
        /// </summary>
        [Description("Entertainment Retail")]
        EntertainmentRetail = 14,

        /// <summary>
        /// <para>Equipment Rental and Leasing</para>
        /// <para>Value = 15</para>
        /// </summary>
        [Description("Equipment Rental and Leasing")]
        EquipmentRentalAndLeasing = 15,

        /// <summary>
        /// <para>Financial</para>
        /// <para>Value = 16</para>
        /// </summary>
        [Description("Financial")]
        Financial = 16,

        /// <summary>
        /// <para>Food and Tobacco Processing</para>
        /// <para>Value = 17</para>
        /// </summary>
        [Description("Food and Tobacco Processing")]
        FoodAndTobaccoProcessing = 17,

        /// <summary>
        /// <para>Inbound Capital Intensive Processing</para>
        /// <para>Value = 18</para>
        /// </summary>
        [Description("Inbound Capital Intensive Processing")]
        InboundCapitalIntensiveProcessing = 18,

        /// <summary>
        /// <para>Inbound Repair and Services</para>
        /// <para>Value = 19</para>
        /// </summary>
        [Description("Inbound Repair and Services")]
        InboundRepairAndServices = 19,

        /// <summary>
        /// <para>Insurance</para>
        /// <para>Value = 20</para>
        /// </summary>
        [Description("Insurance")]
        Insurance = 20,

        /// <summary>
        /// <para>Legal Services</para>
        /// <para>Value = 21</para>
        /// </summary>
        [Description("Legal Services")]
        LegalServices = 21,

        /// <summary>
        /// <para>Non-Durable Merchandise Retail</para>
        /// <para>Value = 22</para>
        /// </summary>
        [Description("Non-Durable Merchandise Retail")]
        Non_DurableMerchandiseRetail = 22,

        /// <summary>
        /// <para>Outbound Consumer Service</para>
        /// <para>Value = 23</para>
        /// </summary>
        [Description("Outbound Consumer Service")]
        OutboundConsumerService = 23,

        /// <summary>
        /// <para>Petrochemical Extraction and Distribution</para>
        /// <para>Value = 24</para>
        /// </summary>
        [Description("Petrochemical Extraction and Distribution")]
        PetrochemicalExtractionAndDistribution = 24,

        /// <summary>
        /// <para>Service Retail</para>
        /// <para>Value = 25</para>
        /// </summary>
        [Description("Service Retail")]
        ServiceRetail = 25,

        /// <summary>
        /// <para>SIG Affiliations</para>
        /// <para>Value = 26</para>
        /// </summary>
        [Description("SIG Affiliations")]
        SIGAffiliations = 26,

        /// <summary>
        /// <para>Social Services</para>
        /// <para>Value = 27</para>
        /// </summary>
        [Description("Social Services")]
        SocialServices = 27,

        /// <summary>
        /// <para>Special Outbound Trade Contractors</para>
        /// <para>Value = 28</para>
        /// </summary>
        [Description("Special Outbound Trade Contractors")]
        SpecialOutboundTradeContractors = 28,

        /// <summary>
        /// <para>Specialty Realty</para>
        /// <para>Value = 29</para>
        /// </summary>
        [Description("Specialty Realty")]
        SpecialtyRealty = 29,

        /// <summary>
        /// <para>Transportation</para>
        /// <para>Value = 30</para>
        /// </summary>
        [Description("Transportation")]
        Transportation = 30,

        /// <summary>
        /// <para>Utility Creation and Distribution</para>
        /// <para>Value = 31</para>
        /// </summary>
        [Description("Utility Creation and Distribution")]
        UtilityCreationAndDistribution = 31,

        /// <summary>
        /// <para>Vehicle Retail</para>
        /// <para>Value = 32</para>
        /// </summary>
        [Description("Vehicle Retail")]
        VehicleRetail = 32,

        /// <summary>
        /// <para>Wholesale</para>
        /// <para>Value = 33</para>
        /// </summary>
        [Description("Wholesale")]
        Wholesale = 33,
    }
}
