// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_ConnectivityToCustomerPremises
    {
        /// <summary>
        /// <para>Internet</para>
        /// <para>Value = 858830000</para>
        /// </summary>
        [Description("Internet")]
        Internet = 858830000,

        /// <summary>
        /// <para>IPSEC</para>
        /// <para>Value = 858830001</para>
        /// </summary>
        [Description("IPSEC")]
        IPSEC = 858830001,

        /// <summary>
        /// <para>Fixed line services</para>
        /// <para>Value = 858830002</para>
        /// </summary>
        [Description("Fixed line services")]
        FixedLineServices = 858830002,
    }
}
