// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_Address1_FreightTerms
    {
        /// <summary>
        /// <para>FOB</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("FOB")]
        FOB = 1,

        /// <summary>
        /// <para>No Charge</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("No Charge")]
        NoCharge = 2,
    }
}
