// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_PerformanceStatus
    {
        /// <summary>
        /// <para>Improving</para>
        /// <para>Value = 858830000</para>
        /// </summary>
        [Description("Improving")]
        Improving = 858830000,

        /// <summary>
        /// <para>Improved</para>
        /// <para>Value = 858830001</para>
        /// </summary>
        [Description("Improved")]
        Improved = 858830001,

        /// <summary>
        /// <para>Same</para>
        /// <para>Value = 858830002</para>
        /// </summary>
        [Description("Same")]
        Same = 858830002,

        /// <summary>
        /// <para>Declined</para>
        /// <para>Value = 858830003</para>
        /// </summary>
        [Description("Declined")]
        Declined = 858830003,
    }
}
