// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_CompanySize
    {
        /// <summary>
        /// <para>Small</para>
        /// <para>Value = 858830000</para>
        /// </summary>
        [Description("Small")]
        Small = 858830000,

        /// <summary>
        /// <para>Medium</para>
        /// <para>Value = 858830001</para>
        /// </summary>
        [Description("Medium")]
        Medium = 858830001,

        /// <summary>
        /// <para>Large</para>
        /// <para>Value = 858830002</para>
        /// </summary>
        [Description("Large")]
        Large = 858830002,
    }
}
