// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_Status
    {
        /// <summary>
        /// <para>Active</para>
        /// <para>Value = 0</para>
        /// </summary>
        [Description("Active")]
        Active = 0,

        /// <summary>
        /// <para>Inactive</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Inactive")]
        Inactive = 1,
    }
}
