// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_ProfileType
    {
        /// <summary>
        /// <para>Retail</para>
        /// <para>Value = 858830002</para>
        /// </summary>
        [Description("Retail")]
        Retail = 858830002,

        /// <summary>
        /// <para>Local</para>
        /// <para>Value = 858830000</para>
        /// </summary>
        [Description("Local")]
        Local = 858830000,

        /// <summary>
        /// <para>GDSP</para>
        /// <para>Value = 858830001</para>
        /// </summary>
        [Description("GDSP")]
        GDSP = 858830001,
    }
}
