// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_PreferredDay
    {
        /// <summary>
        /// <para>Sunday</para>
        /// <para>Value = 0</para>
        /// </summary>
        [Description("Sunday")]
        Sunday = 0,

        /// <summary>
        /// <para>Monday</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Monday")]
        Monday = 1,

        /// <summary>
        /// <para>Tuesday</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Tuesday")]
        Tuesday = 2,

        /// <summary>
        /// <para>Wednesday</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Wednesday")]
        Wednesday = 3,

        /// <summary>
        /// <para>Thursday</para>
        /// <para>Value = 4</para>
        /// </summary>
        [Description("Thursday")]
        Thursday = 4,

        /// <summary>
        /// <para>Friday</para>
        /// <para>Value = 5</para>
        /// </summary>
        [Description("Friday")]
        Friday = 5,

        /// <summary>
        /// <para>Saturday</para>
        /// <para>Value = 6</para>
        /// </summary>
        [Description("Saturday")]
        Saturday = 6,
    }
}
