// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_AccountStatus
    {
        /// <summary>
        /// <para>Active</para>
        /// <para>Value = 858830000</para>
        /// </summary>
        [Description("Active")]
        Active = 858830000,

        /// <summary>
        /// <para>Suspended</para>
        /// <para>Value = 858830001</para>
        /// </summary>
        [Description("Suspended")]
        Suspended = 858830001,

        /// <summary>
        /// <para>Trial</para>
        /// <para>Value = 858830002</para>
        /// </summary>
        [Description("Trial")]
        Trial = 858830002,

        /// <summary>
        /// <para>Closed</para>
        /// <para>Value = 858830003</para>
        /// </summary>
        [Description("Closed")]
        Closed = 858830003,

        /// <summary>
        /// <para>Closed_Bad Debt</para>
        /// <para>Value = 858830004</para>
        /// </summary>
        [Description("Closed_Bad Debt")]
        Closed_BadDebt = 858830004,
    }
}
