// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_AccountType
    {
        /// <summary>
        /// <para>GDSP</para>
        /// <para>Value = 858830000</para>
        /// </summary>
        [Description("GDSP")]
        GDSP = 858830000,

        /// <summary>
        /// <para>GDSP Lite</para>
        /// <para>Value = 858830001</para>
        /// </summary>
        [Description("GDSP Lite")]
        GDSPLite = 858830001,
    }
}
