// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_Address2_AddressType
    {
        /// <summary>
        /// <para>Default Value</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Default Value")]
        DefaultValue = 1,
    }
}
