// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_SubscribedServices
    {
        /// <summary>
        /// <para>Data</para>
        /// <para>Value = 858830000</para>
        /// </summary>
        [Description("Data")]
        Data = 858830000,

        /// <summary>
        /// <para>Voice</para>
        /// <para>Value = 858830001</para>
        /// </summary>
        [Description("Voice")]
        Voice = 858830001,

        /// <summary>
        /// <para>SMS</para>
        /// <para>Value = 858830002</para>
        /// </summary>
        [Description("SMS")]
        SMS = 858830002,

        /// <summary>
        /// <para>GUI</para>
        /// <para>Value = 858830003</para>
        /// </summary>
        [Description("GUI")]
        GUI = 858830003,

        /// <summary>
        /// <para>API</para>
        /// <para>Value = 858830004</para>
        /// </summary>
        [Description("API")]
        API = 858830004,
    }
}
