// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_PreferredMethodOfContact
    {
        /// <summary>
        /// <para>Any</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Any")]
        Any = 1,

        /// <summary>
        /// <para>Email</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Email")]
        Email = 2,

        /// <summary>
        /// <para>Phone</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Phone")]
        Phone = 3,

        /// <summary>
        /// <para>Fax</para>
        /// <para>Value = 4</para>
        /// </summary>
        [Description("Fax")]
        Fax = 4,

        /// <summary>
        /// <para>Mail</para>
        /// <para>Value = 5</para>
        /// </summary>
        [Description("Mail")]
        Mail = 5,
    }
}
