// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_RelationshipType
    {
        /// <summary>
        /// <para>Competitor</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Competitor")]
        Competitor = 1,

        /// <summary>
        /// <para>Consultant</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Consultant")]
        Consultant = 2,

        /// <summary>
        /// <para>Customer</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Customer")]
        Customer = 3,

        /// <summary>
        /// <para>Investor</para>
        /// <para>Value = 4</para>
        /// </summary>
        [Description("Investor")]
        Investor = 4,

        /// <summary>
        /// <para>Partner</para>
        /// <para>Value = 5</para>
        /// </summary>
        [Description("Partner")]
        Partner = 5,

        /// <summary>
        /// <para>Influencer</para>
        /// <para>Value = 6</para>
        /// </summary>
        [Description("Influencer")]
        Influencer = 6,

        /// <summary>
        /// <para>Press</para>
        /// <para>Value = 7</para>
        /// </summary>
        [Description("Press")]
        Press = 7,

        /// <summary>
        /// <para>Prospect</para>
        /// <para>Value = 8</para>
        /// </summary>
        [Description("Prospect")]
        Prospect = 8,

        /// <summary>
        /// <para>Reseller</para>
        /// <para>Value = 9</para>
        /// </summary>
        [Description("Reseller")]
        Reseller = 9,

        /// <summary>
        /// <para>Supplier</para>
        /// <para>Value = 10</para>
        /// </summary>
        [Description("Supplier")]
        Supplier = 10,

        /// <summary>
        /// <para>Vendor</para>
        /// <para>Value = 11</para>
        /// </summary>
        [Description("Vendor")]
        Vendor = 11,

        /// <summary>
        /// <para>Other</para>
        /// <para>Value = 12</para>
        /// </summary>
        [Description("Other")]
        Other = 12,
    }
}
