// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_Category
    {
        /// <summary>
        /// <para>Preferred Customer</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Preferred Customer")]
        PreferredCustomer = 1,

        /// <summary>
        /// <para>Standard</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Standard")]
        Standard = 2,
    }
}
