// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_ChargeType
    {
        /// <summary>
        /// <para>Advance</para>
        /// <para>Value = 858830000</para>
        /// </summary>
        [Description("Advance")]
        Advance = 858830000,

        /// <summary>
        /// <para>Arrears</para>
        /// <para>Value = 858830001</para>
        /// </summary>
        [Description("Arrears")]
        Arrears = 858830001,
    }
}
