// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_Type
    {
        /// <summary>
        /// <para>Corporate</para>
        /// <para>Value = 858830000</para>
        /// </summary>
        [Description("Corporate")]
        Corporate = 858830000,

        /// <summary>
        /// <para>Individual</para>
        /// <para>Value = 858830001</para>
        /// </summary>
        [Description("Individual")]
        Individual = 858830001,
    }
}
