// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_Ownership
    {
        /// <summary>
        /// <para>Public</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Public")]
        @Public = 1,

        /// <summary>
        /// <para>Private</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Private")]
        @Private = 2,

        /// <summary>
        /// <para>Subsidiary</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Subsidiary")]
        Subsidiary = 3,

        /// <summary>
        /// <para>Other</para>
        /// <para>Value = 4</para>
        /// </summary>
        [Description("Other")]
        Other = 4,
    }
}
