// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_StatusReason
    {
        /// <summary>
        /// <para>Active</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Active")]
        Active = 1,

        /// <summary>
        /// <para>Inactive</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("Inactive")]
        Inactive = 2,
    }
}
