// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_Address1_ShippingMethod
    {
        /// <summary>
        /// <para>Airborne</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Airborne")]
        Airborne = 1,

        /// <summary>
        /// <para>DHL</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("DHL")]
        DHL = 2,

        /// <summary>
        /// <para>FedEx</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("FedEx")]
        FedEx = 3,

        /// <summary>
        /// <para>UPS</para>
        /// <para>Value = 4</para>
        /// </summary>
        [Description("UPS")]
        UPS = 4,

        /// <summary>
        /// <para>Postal Mail</para>
        /// <para>Value = 5</para>
        /// </summary>
        [Description("Postal Mail")]
        PostalMail = 5,

        /// <summary>
        /// <para>Full Load</para>
        /// <para>Value = 6</para>
        /// </summary>
        [Description("Full Load")]
        FullLoad = 6,

        /// <summary>
        /// <para>Will Call</para>
        /// <para>Value = 7</para>
        /// </summary>
        [Description("Will Call")]
        WillCall = 7,
    }
}
