// <auto-generated />

using System.ComponentModel;
namespace PluginCodeTest.ProxyClasses
{
    public enum eAccount_PaymentTerms
    {
        /// <summary>
        /// <para>Net 30</para>
        /// <para>Value = 1</para>
        /// </summary>
        [Description("Net 30")]
        Net30 = 1,

        /// <summary>
        /// <para>2% 10, Net 30</para>
        /// <para>Value = 2</para>
        /// </summary>
        [Description("2% 10, Net 30")]
        _2_10_Net30 = 2,

        /// <summary>
        /// <para>Net 45</para>
        /// <para>Value = 3</para>
        /// </summary>
        [Description("Net 45")]
        Net45 = 3,

        /// <summary>
        /// <para>Net 60</para>
        /// <para>Value = 4</para>
        /// </summary>
        [Description("Net 60")]
        Net60 = 4,
    }
}
